### ISSUE TITLE
Whoops! Something went wrong...

### ISSUE THREAD

**Issue by latsa** [kuylar/InnerTube#43]
* LightTube instance this error occured on (tube.kuylar.dev)
* LightTube & InnerTube versions (2023.12.13 / 1.0.27.0)
* The full resource path (/watch?v=-UBaW1OIgTo)
* InnerTube language & region (en_US)

System.NullReferenceException: Object reference not set to an instance of an object.
at InnerTube.EndScreenItem..ctor(JToken json)
at InnerTube.InnerTubePlayer.<>c.<.ctor>b__27_3(JToken x)
at System.Linq.Enumerable.SelectIListIterator`2.MoveNext()
at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonCollectionConverter`2.OnTryWrite(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.Metadata.JsonPropertyInfo`1.GetMemberAndWriteJson(Object obj, WriteStack& state, Utf8JsonWriter writer)
at System.Text.Json.Serialization.Converters.ObjectDefaultConverter`1.OnTryWrite(Utf8JsonWriter writer, T value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonConverter`1.TryWrite(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
at System.Text.Json.JsonSerializer.WriteUsingSerializer[TValue](Utf8JsonWriter writer, TValue& value, JsonTypeInfo jsonTypeInfo)
at System.Text.Json.JsonSerializer.WriteStringUsingSerializer[TValue](TValue& value, JsonTypeInfo jsonTypeInfo)
at AspNetCoreGeneratedDocument.Views_Shared_Player.ExecuteAsync() in /src/LightTube/Views/Shared/Player.cshtml:line 144
at AspNetCoreGeneratedDocument.Views_Youtube_Watch.ExecuteAsync() in /src/LightTube/Views/Youtube/Watch.cshtml:line 15
--- End of stack trace from previous location ---

**Comment by kuylar** [comment]
Fixed, however this update won't be in LightTube until we get around to the .NET 8 update
